sudo: required
dist: bionic
language: cpp
compiler: gcc
before_script:
- sudo ./prep-env.sh
script:
- python ./run-test.py
- doxygen doxygen.cfg
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doc/html
  github_token: "$GH_REPO_TOKEN"
  on:
    branch: master
env:
  global:
    secure: K0Z8tXboTJQZbYxGY5FspmtiTJoXCPmRQn1+NfHds5M14LRryEaGgUp7wtSXfjl3QGWgyoX8qTfVUzlmTCj+OldM2CCu3ubY3qyKcEf0T+QhEaYxLX94+qrlppEvCrCcKLveluNWui2o+FeZXxXG2eSw++MlDpYDk4K0iO56P2uUSY6xoFt+yQSHAtApAyn0M2QUMjXplHWKv7AWPe2L+lRHjeNKxj4vfVmZ+3kC5wxVA7RFFB1Mwq54m6N0wXx5UwLrt9Lw6kGIMwxRDFwRpU9ap25F1tLjFqd9V7eEr+W2z/JkvKj6sBgN7S7W1tJyLUhzwQKbFORkmq+fzSPB0/Ft1wyAFuXDJuf3EMYr1+6JyvkIZnytG2bn3KULJcXOnqs1aagNw59tjDGJtrdTQQ8UvXvG1aINMX2Cr1muBCmEhhHscttErCCP+DPqtusc9ORuL3RQr9cYfPM0RTl23jfcACksxDgkZ92ogeS2q/bhNN1PEdmtG3Yqv+tW5Acdl78MMXP+dDnui773hQ2XATBsXCm7DUDXlcOOvKeE5BmShJmq6fnaW77uUdNKrO7t9ytnSkXY2+7LYfnfqolLzrrFByKnuYWkHccxyvCot9OsqWTNeM/OFgyCgxL4BSCYf6WCkfFZjjBvNlVBWEoWPmqn4hLa16bveRgtMYSdj+8=
