var annotated_dup =
[
    [ "cppbind", null, [
      [ "Binder", "classcppbind_1_1_binder.html", "classcppbind_1_1_binder" ],
      [ "BinderImpBase", "classcppbind_1_1_binder_imp_base.html", "classcppbind_1_1_binder_imp_base" ],
      [ "BoostGDateConverter", "classcppbind_1_1_boost_g_date_converter.html", "classcppbind_1_1_boost_g_date_converter" ],
      [ "BoostPTimeConverter", "classcppbind_1_1_boost_p_time_converter.html", "classcppbind_1_1_boost_p_time_converter" ],
      [ "BoostTimeDurationConverter", "classcppbind_1_1_boost_time_duration_converter.html", "classcppbind_1_1_boost_time_duration_converter" ],
      [ "ClassMissRegException", "classcppbind_1_1_class_miss_reg_exception.html", "classcppbind_1_1_class_miss_reg_exception" ],
      [ "ClassRegister", "classcppbind_1_1_class_register.html", "classcppbind_1_1_class_register" ],
      [ "ClassRegisterBase", "classcppbind_1_1_class_register_base.html", "classcppbind_1_1_class_register_base" ],
      [ "CSVBind", "classcppbind_1_1_c_s_v_bind.html", "classcppbind_1_1_c_s_v_bind" ],
      [ "CSVReader", "classcppbind_1_1_c_s_v_reader.html", "classcppbind_1_1_c_s_v_reader" ],
      [ "CSVRow", "classcppbind_1_1_c_s_v_row.html", "classcppbind_1_1_c_s_v_row" ],
      [ "EnumHelper", "classcppbind_1_1_enum_helper.html", "classcppbind_1_1_enum_helper" ],
      [ "ForeginKeyMissingException", "classcppbind_1_1_foregin_key_missing_exception.html", "classcppbind_1_1_foregin_key_missing_exception" ],
      [ "ForeginTableT", "classcppbind_1_1_foregin_table_t.html", "classcppbind_1_1_foregin_table_t" ],
      [ "ForeignTableInterface", "classcppbind_1_1_foreign_table_interface.html", "classcppbind_1_1_foreign_table_interface" ],
      [ "JsonBind", "classcppbind_1_1_json_bind.html", "classcppbind_1_1_json_bind" ],
      [ "JsonDecodeBinder", "classcppbind_1_1_json_decode_binder.html", "classcppbind_1_1_json_decode_binder" ],
      [ "JsonEncodeBinder", "classcppbind_1_1_json_encode_binder.html", "classcppbind_1_1_json_encode_binder" ],
      [ "JsonFile", "classcppbind_1_1_json_file.html", "classcppbind_1_1_json_file" ],
      [ "MultiJsonFile", "classcppbind_1_1_multi_json_file.html", "classcppbind_1_1_multi_json_file" ],
      [ "Object", "classcppbind_1_1_object.html", "classcppbind_1_1_object" ],
      [ "ObjFactory", "classcppbind_1_1_obj_factory.html", "classcppbind_1_1_obj_factory" ],
      [ "ObjFactoryT", "classcppbind_1_1_obj_factory_t.html", "classcppbind_1_1_obj_factory_t" ],
      [ "ObjWrapperT", "classcppbind_1_1_obj_wrapper_t.html", "classcppbind_1_1_obj_wrapper_t" ],
      [ "ParseErrorException", "classcppbind_1_1_parse_error_exception.html", "classcppbind_1_1_parse_error_exception" ],
      [ "SimpleMapTable", "classcppbind_1_1_simple_map_table.html", "classcppbind_1_1_simple_map_table" ],
      [ "StringConverter", "classcppbind_1_1_string_converter.html", "classcppbind_1_1_string_converter" ],
      [ "StringConverterManager", "classcppbind_1_1_string_converter_manager.html", "classcppbind_1_1_string_converter_manager" ],
      [ "StringConverterT", "classcppbind_1_1_string_converter_t.html", "classcppbind_1_1_string_converter_t" ],
      [ "TimeFormat", "classcppbind_1_1_time_format.html", "classcppbind_1_1_time_format" ],
      [ "TimeStr", "classcppbind_1_1_time_str.html", "classcppbind_1_1_time_str" ]
    ] ]
];