# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



#trigger:
#  - master

jobs:
  - job: "Unit_Test_Ubuntu_1804_Apt"
    pool:
      vmImage: "ubuntu-18.04"
    steps:
      - script: ./devops/prep-env.sh
        displayName: 'prepare env'
      - script: cd test && make test
        displayName: 'run unit test'

  - job: "Sonar_Scan"
    pool:
      vmImage: "ubuntu-18.04"
    steps:
      - script: ./devops/prep-env.sh
        displayName: 'prepare env'
      - script: bash ./sonar-check.sh
        displayName: 'sonar scan'

  - template: devops/build-ubuntu-vcpkg.yml
    parameters:
      name: 'Unit_Test_Ubuntu_1604_Vcpkg'
      image: 'Ubuntu 18.04'
  - template: devops/build-ubuntu-vcpkg.yml
    parameters:
      name: 'Unit_Test_Ubuntu_2004_Vcpkg'
      image: 'Ubuntu 20.04'
