# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
  - master
jobs:
  - job: "unit_test"
    pool:
      vmImage: "ubuntu-18.04"
    steps:
      - script: ./prep-env.sh
        displayName: 'prepare env'
      - script: ./run-unit-test.sh
        displayName: 'run unit test'

  - job: "sonar_scan"
    pool:
      vmImage: "ubuntu-18.04"
    steps:
      - script: ./prep-env.sh
        displayName: 'prepare env'
      - script: bash ./sonar-check.sh
        displayName: 'sonar scan'

